Resources: 
  UsersTable: 
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UsersTable
      AttributeDefinitions: 
          - AttributeName: id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema: 
          - AttributeName: id
            KeyType: HASH
      
      GlobalSecondaryIndexes:
      - IndexName: emailIndex
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        Projection:
          ProjectionType: ALL